car_inventory/models.py
# standard imports
import uuid
from datetime import datetime
import secrets

# 3rd party imports
from flask_sqlalchemy import SQLAlchemy
#Adding Flask security for passwords
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

#User model creation
class User(db.Model):
    id = db.Column(db.String, primary_key= True)
    first_name = db.Column(db.String(50), nullable = True, default = '')
    last_name = db.Column(db.String(50), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = '')
    g_auth_verify = db.Column(db.Boolean, default = False)
    token = db.Column(db.String, default='', unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, email, first_name = '', last_name='', id='', password='', token='', g_auth_verify=False):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify

    def set_id(self):
        return str(uuid.uuid4())

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def set_token(self, length):
        return secrets.token_hex(length)

    def __repr__(self):
        return f'User {self.email} has been added to the database.'

car_inventory/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Email, EqualTo

class UserLoginForm(FlaskForm):
    #set up the email, password, confirm, and submitt button
    email = StringField('Email', validators=[InputRequired(), Email()])
    password = PasswordField('Password', validators=[InputRequired(), EqualTo('confirm', message = 'Your passwords do not match, please try again.')])
    confirm = PasswordField('Confirm Password')
    submit_button = SubmitField()

car_inventory/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from config import Config
from .site.routes import site
from .api.routes import api
from .authentication.routes import auth
from .models import db as root_db


app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(api)
app.register_blueprint(auth)

app.config.from_object(Config)

root_db.init_app(app)
migrate = Migrate(app, root_db)

car_inventory/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('getdata')
def getdata():
    return {'some':'value'}

car_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, flash, url_for, redirect

# Project file imports
from car_inventory.forms import UserLoginForm
from car_inventory.models import User, db

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            # Add user into Database
            user = User(email, password = password)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully a user account for {email}.','user-created')
            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please check your form.')


    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    return render_template('signin.html', form=form)

car_inventory/site/routes.py
from flask import Blueprint, render_template


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/sell_trade')
def sell_trade():
    return render_template('sell_trade.html')

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Inventory API</title>
</head>
<body>
    <nav class="ct-nav">
        <div><img src="../static/images/fox-logo-01.png.webp" alt="Fox Logo"></div>

        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Search Inventory</li>
                </a>
                <a href="{{ url_for('site.sell_trade')}}">
                    <li>Sell/Trade</li>
                </a>
                <a href="">
                    <li>Car Reviews</li>
                </a>
                <a href="">
                    <li>Log Out</li>
                </a>
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
            </ul>
        </div>
    </nav>

    {% block content%}
    {% endblock content%}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter Email Here") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter Password Here") }}
        </fieldset>
        <fieldset id="confirm-field">
            {{ form.confirm.label }}
            {{ form.confirm(class = "form-control", placeholder = "Confirm Password") }}
        </fieldset>

        <!-- Submit Button -->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>